--Trabajo Proyecto Final Programación 5
/* Autores:
* Andres Rojas
* Ana Calvo
* Esteban Mora
* William Herrera*/


/** SE SELECCIONA LA BASE DE DATOS CREADA**/
USE SISTEMA_GESTION_ACADEMICA
GO

-- STORE PROCEDURE UPDATE USUARIOS
CREATE PROCEDURE sp_ActualizarUsuario
    @CEDULA INT,
    @NOMBRE VARCHAR(20),
    @APELLIDOS VARCHAR(30),
    @EDAD INT,
    @CORREO VARCHAR(100),
    @CLAVE NVARCHAR(MAX),
    @CODIGODOCENTE VARCHAR(10),
    @FECHA DATETIME,
    @ID_ROLLES INT,
    @ACTIVO BIT
AS
BEGIN
    IF EXISTS(SELECT 1 FROM USUARIO WHERE CEDULA = @CEDULA)
    BEGIN
        UPDATE USUARIO
        SET
            NOMBRE = @NOMBRE,
            APELLIDOS = @APELLIDOS,
            EDAD = @EDAD,
            CORREO = @CORREO,
            CLAVE = @CLAVE,
            CODIGODOCENTE = @CODIGODOCENTE,
            FECHA = @FECHA,
            ID_ROLLES = @ID_ROLLES,
            ACTIVO = @ACTIVO
        WHERE CEDULA = @CEDULA;
    END
    ELSE
    BEGIN
        PRINT 'EL USUARIO NO EXISTE';
    END
END
GO

--STORE PROCEDURE UPDATE OFERTA ACADEMICA
CREATE PROCEDURE sp_ActualizarOfertaAcademica
    @ID_OFERTA INT,
    @NOMBREOFERTA VARCHAR(15),
    @ID_CURSO VARCHAR(10),
    @ID_SEDE INT,
    @ID_CUATRIMESTRE INT,
    @CEDULA_DOCENTE INT,
    @AÑO DATETIME,
    @ID_HORARIO INT,
    @GRUPO INT,
    @ESTADO BIT,
    @USUARIO INT
AS
BEGIN
    IF EXISTS(SELECT 1 FROM OFERTA_ACADEMICA WHERE ID_OFERTA = @ID_OFERTA)
    BEGIN
        UPDATE OFERTA_ACADEMICA
        SET
            ID_CURSO = @ID_CURSO,
            ID_SEDE = @ID_SEDE,
            ID_CUATRIMESTRE = @ID_CUATRIMESTRE,
            CEDULA_DOCENTE = @CEDULA_DOCENTE,
            AÑO = @AÑO,
            ID_HORARIO = @ID_HORARIO,
            GRUPO = @GRUPO,
            ESTADO = @ESTADO,
            USUARIO = @USUARIO
        WHERE ID_OFERTA = @ID_OFERTA;
    END
    ELSE
    BEGIN
        PRINT 'LA OFERTA ACADÉMICA NO EXISTE';
    END
END
GO

--STORE PROCEDURE UPDATE DIRECCION
CREATE PROCEDURE sp_ActualizarDireccion
    @ID_DIRECCION INT,
    @DIRECCION VARCHAR(150),
    @CEDULA INT
AS
BEGIN
    IF EXISTS(SELECT 1 FROM DIRECCION WHERE ID_DIRECCION = @ID_DIRECCION)
    BEGIN
        UPDATE DIRECCION
        SET
            DIRECCION = @DIRECCION,
            CEDULA = @CEDULA
        WHERE ID_DIRECCION = @ID_DIRECCION;
    END
    ELSE
    BEGIN
        PRINT 'LA DIRECCIÓN NO EXISTE';
    END
END
GO

---STORE PROCEDURE UPDATE PLAN DE CURSO
CREATE PROCEDURE sp_ActualizarPlanCurso
	@CODIGOPLAN VARCHAR(10),
	@NOMBREPLAN VARCHAR(10),
	@ID_CARRERA VARCHAR(15)
AS
BEGIN 
	SET NOCOUNT ON
	IF EXISTS (SELECT 1 FROM PLAN_CURSO WHERE CODIGOPLAN = @CODIGOPLAN)
	BEGIN
		UPDATE PLAN_CURSO
		SET 
		NOMBREPLAN =@NOMBREPLAN,
		ID_CARRERA = @ID_CARRERA
		WHERE CODIGOPLAN = @CODIGOPLAN;
	END
	ELSE
	BEGIN 
		PRINT'PLAN DE CURSO NO EXISTE'
	END
END
GO

---STORE PROCEDURE UPDATE TELEFONO
CREATE PROCEDURE sp_ActualizarTelefono
    @ID_TELEFONO INT,
    @NUMERO INT,
    @CEDULA INT
AS
BEGIN
    IF EXISTS(SELECT 1 FROM TELEFONO WHERE ID_TELEFONO = @ID_TELEFONO)
    BEGIN
        UPDATE TELEFONO
        SET
            NUMERO = @NUMERO,
            CEDULA = @CEDULA
        WHERE ID_TELEFONO = @ID_TELEFONO;
    END
    ELSE
    BEGIN
        PRINT 'EL NÚMERO DE TELÉFONO NO EXISTE';
    END
END
GO

---STORE PROCEDURE UPDATE CURSO
CREATE PROCEDURE sp_ActualizarCurso
    @ID_CURSO VARCHAR(10),
    @NOMBRECURSO VARCHAR(20),
    @CREDITO INT,
    @BLOQUE INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS(SELECT 1 FROM CURSO WHERE ID_CURSO = @ID_CURSO)
    BEGIN
        UPDATE CURSO
        SET
            NOMBRECURSO = @NOMBRECURSO,
            CREDITO = @CREDITO,
            BLOQUE = @BLOQUE
        WHERE ID_CURSO = @ID_CURSO;
    END
    ELSE
    BEGIN
        PRINT 'EL CURSO NO EXISTE';
    END
END
GO
