--Trabajo Proyecto Final Programación 5
/* Autores:
* Andres Rojas
* Ana Calvo
* Esteban Mora
* William Herrera*/

/*PENDIENTE = 1, ACEPTADO = 2, RECHAZADO = 3*/
USE [SISTEMA_GESTION_ACADEMICA]
GO

INSERT INTO [dbo].[ESTADO_SOLICITUD]([NOMBRE_ESTADO])
     VALUES('PENDIENTE'),('ACEPTADO'),('RECHAZADO')
GO

INSERT INTO [dbo].[ROLLES]([NOMBREROLL])
     VALUES
           ('ADMINISTRADOR'), ('COORDINADOR'), ('DOCENTE'), ('SOPORTE')
GO 

SELECT * from dbo.ESTADO_SOLICITUD
exec [dbo].[NEW_USER_REQUEST] 00000001,'WILLIAM','HERRERA ARAYA',26,'WILLIAM_HERRERA1@ULATINA.NET', 'PATITO',NULL,2

SELECT * FROM [dbo].[SOLICITUD_USUARIO]
GO
SELECT * FROM [dbo].[USUARIO]
GO

