#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndOfertaAcademica.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SISTEMA_GESTION_ACADEMICA")]
	public partial class conexionLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public conexionLinqDataContext() : 
				base(global::BackEndOfertaAcademica.Properties.Settings.Default.SISTEMA_GESTION_ACADEMICAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NEW_USER")]
		public int NEW_USER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA", DbType="Int")] System.Nullable<int> cEDULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(20)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EDAD", DbType="Int")] System.Nullable<int> eDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(100)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLAVE", DbType="NVarChar(MAX)")] string cLAVE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGODOCENTE", DbType="VarChar(10)")] string cODIGODOCENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA", DbType="DateTime")] System.Nullable<System.DateTime> fECHA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ROLLES", DbType="Int")] System.Nullable<int> iD_ROLLES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTIVO", DbType="Bit")] System.Nullable<bool> aCTIVO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA, nOMBRE, aPELLIDOS, eDAD, cORREO, cLAVE, cODIGODOCENTE, fECHA, iD_ROLLES, aCTIVO);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
